import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{/* You can add meta tags, title, etc. here */}</head>
      <body className={inter.className}>
        <NextUIProvider>
          {children}
          <ToastContainer /> {/* Add ToastContainer here */}
        </NextUIProvider>
      </body>
    </html>
  );
}
